### PR TITLE
extended CLI (create projects and templating export)

### PR DESCRIPTION
**Pull request by felixlohmeier**
- Extended CLI
  - new commands: create, delete, info
  - added support for templating in export command
  - allow user to specify project by name
  - one-file-executables for linux and windows
- Added Dockerfile
- Added chapter "Usage" to README
- Refactored new_project()

Paul, maybe you want to "cherry-pick"? The code quality should be better than my first pull request half a year ago but I am still learning. Please let me know if you have any advice on how to better align to your codebase.

### CODE REVIEW

**Comment by paulmakepeace** [comment]
Thanks @felixlohmeier - let me know when you'd like a review for this. I haven't looked at it yet but happy to when you're ready

**Comment by felixlohmeier** [comment]
Oh, hi @paulmakepeace, welcome back... are you going to work on this project again? That would be great!

If you welcome and review contributions again, I will make another non-obstrusive pull request in the next weeks (I started to publish my fork, so the master branch has run apart (README.md etc.).

There are others working on porting your code to Python 3 and making tests work again with OpenRefine 3.x:
* @joseboveda https://github.com/joseboveda/refine-client-py (pull request #13)
* @dbutlerdb https://github.com/dbutlerdb/refine-client-py (pull requests #17 #18)
  * some tests by @psychemedia in https://github.com/ouseful-PR/refine-client-py

Maybe that is more pressing because of the Python 2 countdown? I suggest to review these contributions first. Then I could make a new pull request based on merged Python 3 code?

Upgrading to Python 3 would also make it easier to use the client in Jupyter. There are some new exciting opportunities using binder (with [openrefineder](https://github.com/betatim/openrefineder)). @psychemedia has explored these here:
* https://nbviewer.jupyter.org/github/ouseful-PR/openrefineder/blob/master/notebooks/OpenRefine%20Demos.ipynb
* https://blog.ouseful.info/2019/02/10/openrefine-running-in-mybinder-several-ways/
* https://github.com/OpenRefine/OpenRefine/wiki/Jupyter

**Comment by paulmakepeace** [comment]
Thanks for the feedback @felixlohmeier !

Back when OR 3 was released we had some quirks but hopefully that's all passed at this point.

I like PR #13 for its minimalism right now; I'd like to get a working python 3 version that's passing tests and runs correctly in OpenRefine 3.2 with the least amount of shenanigans. (E.g. while I think updating it from saying google.refine is worthwhile it muddies up the PR and is a significant breaking API change). I'd also like to keep whitespace/linting/etc stuff in its own PR for readability.

After that perhaps we can get any essential changes that @dbutlerdb came up with.

Also thanks to @psychemedia for testing these PRs - if you're still around and up for helping with that (again) that would be great!

**Comment by psychemedia** [comment]
@paulmakepeace I can try to find a bit of time to tinker with this again; would be great to have a canonical py3 version of the client available.

Not strictly related to the OR py client, but in the ballpark, IIRC I also got stuck on linking a [py based linked reconciliation service](https://github.com/OpenRefine/OpenRefine/issues/1952) which I need to revisit...

**Comment by felixlohmeier** [comment]
Hey @paulmakepeace
> let me know when you'd like a review for this. I haven't looked at it yet but happy to when you're ready

I have realigned the code in the fork as much as possible to the Python Client Library. There are a few things I can contribute to the core, I think. These are the new pull requests (and I'm closing this general one now):
* OpenRefine defaults to guessCellValueTypes=False since 2.6 https://github.com/paulmakepeace/refine-client-py/pull/21
* added method for templating export https://github.com/paulmakepeace/refine-client-py/pull/22
* Script for running tests with different OpenRefine and Java versions https://github.com/paulmakepeace/refine-client-py/pull/23

I won't be able to work on the project for a few months. After the break I'll work on the tests in #19 and the port to Python 3.

**Pull request closed without merging**
